# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c32bcf747b8fd8ddb7f27dba7e731870d0ae15e99717fd8dde75a57e9624a32bbb846c8263dbb0db28755eb9d7cd8d2e79b73c8a70f102d5f2179925dadde7b0

test:
  secret_key_base: 0e88186495d2640870c7dd0ece61516b64f9530128ac1ca3a12238a03c2e65bd42cb772581370147d65193e3492293fa5531b9ca45f00df89fe8ebba5a48e7a0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
